name: CI/CD (Self-Hosted -> Docker Compose)

on:
  push:
    branches: [ "main" ]

jobs:
  pipeline:
    runs-on: self-hosted   # รันบนเซิร์ฟเวอร์ที่บ้าน 
    steps:
      # 1) Checkout source code
      - name: 1) Checkout
        uses: actions/checkout@v4

      # 2) Build + Run Unit Test 
      - name: 2) Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: 2.1) API tests 
        run: |
          npm ci || true
          npm test --if-present "

      - name: 2.2) Web build check 
        working-directory: telemed-web
        run: |
          npm ci || true
          npm run build --if-present "

      # 3) Build Docker Image (ด้วย compose) 
      - name: 3) Write .env from Secrets
        run: |
          cat > .env <<'EOF'
          ${{ secrets.ENV_FILE }}
          EOF

      # 4) Deploy ไปยัง Docker Compose environment (เครื่องนี้เลย)
      - name: 4) docker compose build & up
        run: |
          set -e
          docker compose build --pull
          docker compose up -d --remove-orphans
          docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"

      # 5) Run Integration Test หลัง deploy
      - name: 5.1) Healthcheck API
        run: |
          set -e
          code=$(curl -s -o /tmp/api_health.json -w "%{http_code}" http://127.0.0.1/api/health || true)
          echo "API HTTP $code"
          cat /tmp/api_health.json 2>/dev/null || true
          test "$code" = "200"

      - name: 5.2) Healthcheck Web
        run: |
          set -e
          code=$(curl -sI -o /dev/null -w "%{http_code}" http://127.0.0.1/ || true)
          echo "WEB HTTP $code"
          test "$code" = "200" -o "$code" = "304" -o "$code" = "204"   # ยืดหยุ่นเล็กน้อย
