name: CI/CD (Self-Hosted -> Docker Compose)

on:
  push:
    branches: [ "main" ]

jobs:
  pipeline:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash

    # แมป secrets -> env เพื่อใช้ตรวจใน if: (VS Code จะไม่ฟ้อง)
    env:
      DOCKERHUB_USERNAME_ENV: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN_ENV: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      # 1) Checkout source code
      - name: 1) Checkout
        uses: actions/checkout@v4

      # 2) Setup Node
      - name: 2) Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 2.1) API tests
      - name: 2.1) API tests
        run: |
          npm ci || true
          npm test --if-present

      # 2.2) Web build check
      - name: 2.2) Web build check
        working-directory: telemed-web
        run: |
          npm ci || true
          npm run build --if-present

      # 3) (Optional) Docker Hub login – เช็ค env ที่มาจาก secrets
      - name: 3) Docker Hub login
        if: ${{ env.DOCKERHUB_USERNAME_ENV != '' && env.DOCKERHUB_TOKEN_ENV != '' }}
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ env.DOCKERHUB_USERNAME_ENV }}
          password: ${{ env.DOCKERHUB_TOKEN_ENV }}

      # 4) Write .env from Secrets
      - name: 4) Write .env from Secrets
        run: |
          set -e
          printf "%s" "${{ secrets.ENV_FILE }}" > .env
          awk -F= '/^[A-Za-z0-9_]+=/ {print "ENV KEY:", $1}' .env

      # 5) Deploy with Docker Compose (ใช้ --env-file ให้ชัดเจน)
      - name: 5) docker compose build & up
        run: |
          set -e
          ls -la .
          test -f .env
          test -f docker-compose.yml
          docker compose --env-file .env build --pull
          docker compose --env-file .env up -d --remove-orphans
          docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"

      # 6) Healthchecks
      - name: 6.1) Healthcheck API
        run: |
          set -e
          code=$(curl -s -o /tmp/api_health.json -w "%{http_code}" http://127.0.0.1/api/health || true)
          echo "API HTTP $code"
          cat /tmp/api_health.json 2>/dev/null || true
          if [[ "$code" != "200" ]]; then
            echo "API unhealthy"
            exit 1
          fi

      - name: 6.2) Healthcheck Web
        run: |
          set -e
          code=$(curl -sI -o /dev/null -w "%{http_code}" http://127.0.0.1/ || true)
          echo "WEB HTTP $code"
          case "$code" in
            200|204|304) echo "WEB ok" ;;
            *) echo "WEB unhealthy"; exit 1 ;;
          esac
